"""empty message

Revision ID: 161ead395ea4
Revises: 222a82f72833
Create Date: 2021-12-19 02:38:16.974380

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '161ead395ea4'
down_revision = '222a82f72833'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('쿠팡조회결과_csv')
    op.drop_column('product', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('name', mysql.VARCHAR(length=145), nullable=True))
    op.create_table('쿠팡조회결과_csv',
    sa.Column('name', mysql.VARCHAR(length=145), nullable=True),
    sa.Column('url', mysql.VARCHAR(length=290), nullable=True),
    sa.Column('img_url', mysql.VARCHAR(length=156), nullable=True),
    sa.Column('price', mysql.INTEGER(), autoincrement=False, nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
