"""empty message

Revision ID: e25584859797
Revises: 161ead395ea4
Create Date: 2021-12-19 16:43:50.924416

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e25584859797'
down_revision = '161ead395ea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product2')
    op.drop_column('product', 'name')
    op.drop_column('product', 'url')
    op.drop_column('product', 'img_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('img_url', mysql.LONGTEXT(), nullable=True))
    op.add_column('product', sa.Column('url', mysql.LONGTEXT(), nullable=True))
    op.add_column('product', sa.Column('name', mysql.LONGTEXT(), nullable=True))
    op.create_table('product2',
    sa.Column('name', mysql.LONGTEXT(), nullable=True),
    sa.Column('url', mysql.LONGTEXT(), nullable=True),
    sa.Column('img_url', mysql.LONGTEXT(), nullable=True),
    sa.Column('price', mysql.INTEGER(), autoincrement=False, nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
